# 服务相关配置
server:
  address: ":3699"
  tplPath: "view" # 模板文件路径
  staticPrefix: "static" # 静态资源路由前缀
  staticPath: "public" # 静态资源目录
  staticSuffix: "png,jpg,jpeg,gif,mp4,css,js" # 静态资源文件支持的类型

# log日志配置
log:
  path: "logs"
  name: "log"
  model: "file" # console | file
  maxAge: 30 # 日志多少天后自动删除, 以天为单位